### ISSUE TITLE
More Recorded slots in the future?

### ISSUE THREAD

**Issue by Sheidyn** [UnknownX7/ARealmRecorded#1]
Hello! I've been using this plugin and i must say this is amazing and it opens up for a lot of potential in content creation! I am very grateful for your work and i will use it a lot from now on, it's actually amazing!

I wanted to ask how does recording slots work. Are they server sided? Or is it possible to save locally said recording in the future to be able to get more slots? Currently we can only have up to 3 and only keep 2 of them via locking. I was wondering if this is something that could be possible in the future, or the way it's handled it is just not possible.

Thanks again and i will look forward to any updates to this add-on in the future!

**Comment by UnknownX7** [comment]
They are entirely clientside. Natively, increasing the slots would probably be rather difficult as they are hardcoded to 3 in several places. However, I do have plans to expand it through an extra ImGui menu in a similar fashion to the one during playback.

In the meantime, you can save recordings for later by simply renaming them inside `Documents\My Games\FINAL FANTASY XIV - A Realm Reborn\replay`. Just remember they don't work across different game versions. I plan to attempt to fix old recordings in the future, but there will still unfortunately be a limit to how accurate they can be depending on ability changes.

**Comment by UnknownX7** [comment]
As of b0d04c5605f9d677b83540f5d2669c88d510efa9, up to 30 recordings will be saved and deleted automatically unless renamed by double clicking them, which will keep them permanently.
