### ISSUE TITLE
issue with long recordings

### ISSUE THREAD

**Issue by JackieM3bs** [UnknownX7/ARealmRecorded#20]
I'm not able to play recordings of DSR or TOP Ultimates, these recordings are about 1.5 hours long and whenever I start the recording the client will crash. Recordings were taken yesterday and are not from a previous patch. Short recordings of other raids work fine with no issues. Posted the Dalamud crash log if it helps...

[dalamud_appcrash_20240221_142310_598_93568.log](https://github.com/UnknownX7/ARealmRecorded/files/14366710/dalamud_appcrash_20240221_142310_598_93568.log)

**Comment by Lusaca87** [comment]
The Problem also exists here:

Stacktrace maybe it helps
![image](https://github.com/user-attachments/assets/6983ffb6-6abf-42f9-a199-c364305fea4c)
