### ISSUE TITLE
Will update for dawntrail?

### ISSUE THREAD

**Issue by CureFlora** [UnknownX7/ARealmRecorded#23]
Will update for dawntrail?

**Comment by UnknownX7** [comment]
Yes, but I'm unable to give an exact estimate of when it will be fixed. Dawntrail changed a lot of its functions.

**Comment by CureFlora** [comment]
Ah don't worry. Just I glad to see addon not abandoned. There are so many videos waiting to be recorded.

**Comment by zyzolol** [comment]
Thank you so much!

I love this addon.

**Comment by Flukomi** [comment]
> Yes, but I'm unable to give an exact estimate of when it will be fixed. Dawntrail changed a lot of its functions.

Thanks for not abandonning this awesome addon ! :) hope to see it again in the future

**Comment by Foxcubs** [comment]
Hi, do you have ETA?
I'm a big fan of yours and look forward to the day can use this plugin again.

**Comment by CureFlora** [comment]
I check it every day but yeah (

**Comment by UnknownX7** [comment]
Currently looking to have it available tomorrow, but it may have reduced playback functionality for a little longer until I can find a reliable solution for one of the issues caused by Dawntrail changes.
