### ISSUE TITLE
Plugin controls UI disappears when there is a loading screen within Playback mode

### ISSUE THREAD

**Issue by fhn101** [UnknownX7/ARealmRecorded#3]
## Expected Behavior

The additional plugin controls UI should be available at all times during the playback session.

## Actual Behavior

The UI appears initially, but if there is a loading screen (such as jumping to a chapter, or loading a boss fight transition) the UI disappears.

## Steps to Reproduce the Problem

  1. Record a duty
  2. Go into Playback mode and jump to a chapter which has a loading screen.

## Suggestions to Fix the Problem

I would suggest maybe adding a command to re-draw the UI (such as `/record ui` or even just `/arrec`).

## Specifications

  - Version: v0.4.0.0

**Comment by Valgrifer** [comment]
I have same issue, when I jump to a chapter if a custom speed play is selected
