### ISSUE TITLE
Cannot Record: not newest version

### ISSUE THREAD

**Issue by EnderByEndera** [UnknownX7/ARealmRecorded#6]
Hi~ I'm a FFXIV Chinese player and I'm tring to share the recorded file to another player so that another player can use his own recorder to see the total procedure of one raid. However, I find that if I share the recorded file to another player, he cannot use it because the game will warn that the file is not the newest version. I'm wondering whether there is a way to solve the problem?
![image](https://user-images.githubusercontent.com/43458191/201617890-144f8f66-a699-4d93-b07b-36a04b28083f.png)

**Comment by UnknownX7** [comment]
The game menu checks if the character is the same one as the recorder, you will need to select the recording via the ImGui window on the right to bypass it.

**Comment by EnderByEndera** [comment]
Thanks for the comment!! Just click the recording filename right in the ImGui window and the problem is solved~~
